tech_stack = {
    "Page builders": [], "Webmail": [], "Development": [], "Programming languages": [],
    "Databases": [], "Authentication": [], "Web frameworks": [], "Web servers": [],
    "JavaScript frameworks": [], "Tag managers": [], "Security": [], "RUM": [],
    "Performance": [], "Marketing automation": [], "Live chat": [], "JavaScript libraries": [],
    "Font scripts": [], "Email": [], "CDN": [], "Analytics": [], "Affiliate programs": [],
    "Advertising": [], "Accessibility": [], "A/B Testing": [], "Miscellaneous": [],
}

tech_keywords = {
    "Page builders": ["bubble", "wix", "wordpress", "squarespace", "webflow", "elementor", "divi"],
    "Webmail": ["microsoft 365", "gmail", "zoho mail", "yahoo mail", "outlook"],
    "Development": ["firebase", "styled-components", "emotion", "django", "flask", "laravel", "ruby on rails", "node.js", "webpack", "babel"],
    "Programming languages": ["node.js", "python", "ruby", "php", "java", "javascript", "typescript", "go", "swift", "kotlin", "c#", "rust"],
    "Databases": ["firebase", "mongodb", "mysql", "postgresql", "sqlite", "redis", "dynamodb", "oracle", "mariadb"],
    "Authentication": ["facebook login", "google sign-in", "auth0", "okta", "oauth", "jwt", "saml"],
    "Web frameworks": ["bubble", "express", "django", "flask", "laravel", "ruby on rails", "spring", "angular", "react", "vue", "asp.net", "symfony"],
    "Web servers": ["express", "nginx", "apache", "iis", "caddy", "lighttpd", "tomcat"],
    "JavaScript frameworks": ["styled-components", "emotion", "react", "angular", "vue", "svelte", "ember", "backbone", "next.js", "nuxt.js"],
    "Tag managers": ["google tag manager", "adobe tag manager", "tealium"],
    "Security": ["recaptcha", "cloudflare", "sucuri", "aws shield", "security headers", "ssl", "https", "csp"],
    "RUM": ["cloudflare browser insights", "new relic", "datadog", "appdynamics", "dynatrace"],
    "Performance": ["cloudflare rocket loader", "cloudflare zaraz", "priority hints", "lighthouse", "pagespeed insights"],
    "Marketing automation": ["aweber", "optinmonster", "hubspot", "marketo", "mailchimp", "pardot", "salesforce"],
    "Live chat": ["crisp live chat", "intercom", "drift", "zendesk", "livechat", "tawk.to"],
    "JavaScript libraries": ["jquery", "jquery migrate", "core-js", "clipboard.js", "jquery ui", "lodash", "underscore", "moment.js", "axios"],
    "Font scripts": ["google font api", "adobe fonts", "typekit", "fontawesome"],
    "Email": ["aweber", "microsoft 365", "gmail", "mailgun", "sendgrid", "smtp", "postmark"],
    "CDN": ["cloudflare", "jsdelivr", "cdnjs", "akamai", "fastly", "maxcdn", "aws cloudfront"],
    "Analytics": ["cloudflare browser insights", "vwo", "google analytics", "mixpanel", "heap", "segment", "hotjar", "matomo"],
    "Affiliate programs": ["social snowball", "firstpromoter", "impact", "refersion", "tapfiliate", "shareasale"],
    "Advertising": ["google ads", "bing ads", "facebook ads", "linkedin ads", "twitter ads", "adroll"],
    "Accessibility": ["equalweb", "nagich", "accessibe", "wave", "axe", "userway"],
    "A/B Testing": ["vwo", "optimizely", "ab tasty", "convert", "google optimize"],
    "Miscellaneous": ["open graph", "http/3", "schema.org", "json-ld", "websockets", "pwa", "amp"],
}
